general {
    lock_cmd = ~/.local/share/quickshell-lockscreen/lock.sh
    before_sleep_cmd = ~/.local/share/quickshell-lockscreen/lock.sh
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout = 600
    on-timeout = ~/.local/share/quickshell-lockscreen/lock.sh
}

listener {
    timeout = 660
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
