[general]
framerate = 60
bars = 0
[input]
method = pulse
source = auto
[output]
method = ncurses
[color]
gradient = 1
gradient_count = 3
gradient_color_1 = '#8f0c18'
gradient_color_2 = '#ff3045'
gradient_color_3 = '#ffd080'
