foreground #dcecff
background #111522
selection_foreground #ffffff
selection_background #3b3458
cursor #f0a3d9
cursor_text_color #111522
color0 #111522
color8 #53647f
color1 #f0a3d9
color9 #f0a3d9
color2 #9de2d0
color10 #b4e8a9
color3 #f0c6e4
color11 #ffe0a3
color4 #69b8e8
color12 #63a9ff
color5 #c792ea
color13 #e2b8f5
color6 #69e6ff
color14 #9de6ff
color7 #dcecff
color15 #ffffff
