[general]
framerate = 60
bars = 0

[input]
method = pulse
source = auto

[output]
method = ncurses

[color]
gradient = 1
gradient_count = 3
gradient_color_1 = '#89dceb'
gradient_color_2 = '#f38ba8'
gradient_color_3 = '#fab387'
