[general]
framerate = 60
bars = 0

[input]
method = pulse
source = auto

[output]
method = ncurses

[color]
gradient = 1
gradient_count = 3
gradient_color_1 = '#65c7a6'
gradient_color_2 = '#e8b870'
gradient_color_3 = '#d4e7dd'
