foreground #ffe2b8
background #151312
selection_foreground #fff2dc
selection_background #5a3524
cursor #ff9f1c
cursor_text_color #151312
color0 #090d19
color8 #76675c
color1 #e85d04
color9 #ff8c42
color2 #d9a441
color10 #e7c46a
color3 #ffb703
color11 #ffd166
color4 #e68a00
color12 #ffad33
color5 #ff6b1a
color13 #ff8a3d
color6 #ff9f1c
color14 #ffc04d
color7 #ffe2b8
color15 #fff5e6
