foreground #8ccfff
background #070d17
selection_foreground #e7f4ff
selection_background #164569
cursor #31b7ff
cursor_text_color #070d17
color0 #0d1624
color8 #536a81
color1 #ff6e77
color9 #ff8991
color2 #87d7b6
color10 #9ae6c6
color3 #f5c16c
color11 #ffd68a
color4 #198fd5
color12 #59c8ff
color5 #9f9ce8
color13 #b8b2ff
color6 #31b7ff
color14 #70d0ff
color7 #8ccfff
color15 #e8f6ff
