foreground #9aeaff
background #080b16
selection_foreground #f4f6ff
selection_background #34305b
cursor #00d9ff
cursor_text_color #080b16
color0 #090d19
color8 #53617a
color1 #ff5277
color9 #ff7892
color2 #52e0ca
color10 #75f0d9
color3 #f4c96b
color11 #ffe08d
color4 #19aef2
color12 #58c5ff
color5 #f02bd4
color13 #ff64e5
color6 #00d9ff
color14 #56efff
color7 #9aeaff
color15 #e4fbff
