foreground #d9f7ff
background #090713
selection_foreground #f5efff
selection_background #34205b
cursor #00e5ff
cursor_text_color #090713
color0 #090d19
color8 #53517a
color1 #ff3d9a
color9 #ff70b4
color2 #45d9d0
color10 #70f0df
color3 #f4cf6b
color11 #ffe08d
color4 #247cf0
color12 #58c5ff
color5 #d83cff
color13 #ff64e5
color6 #00e5ff
color14 #56efff
color7 #d9f7ff
color15 #e4fbff
