foreground #e3e1dc
background #080b0d
selection_foreground #ffffff
selection_background #29333b
cursor #9ec5e8
cursor_text_color #080b0d
color0 #080b0d
color8 #4e565b
color1 #a87570
color9 #c58d85
color2 #9aab99
color10 #b5c5b0
color3 #c7bda7
color11 #ded1b7
color4 #7897b1
color12 #9ec5e8
color5 #887f8d
color13 #b2a7b5
color6 #9ec5e8
color14 #c1ddf2
color7 #e3e1dc
color15 #ffffff
