foreground #dce9ff
background #071223
selection_foreground #ffffff
selection_background #234a72
cursor #ff7566
cursor_text_color #071223
color0 #071223
color8 #47607d
color1 #ff7566
color9 #ff9b8e
color2 #8fd694
color10 #b4e8a9
color3 #ffc878
color11 #ffe0a3
color4 #3f87c9
color12 #63a9ff
color5 #c49be8
color13 #d9b9ff
color6 #63c7ff
color14 #8ee0ff
color7 #dce9ff
color15 #ffffff
